"""Trial-report rendering and quick-look plotting.

:func:`write_trial_report` produces a self-contained HTML page summarising a
single :class:`ResponsePrediction`: predicted response distribution, the two
counterfactual distributions, and the IPCC-style confidence tier. The page
embeds the audio as a base64 ``<audio>`` element so it can be archived and
shared without external dependencies.
"""
from __future__ import annotations

import base64
import html
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orcadolittle.core.predict import ResponsePrediction


def write_trial_report(prediction: ResponsePrediction, *, path: str | Path) -> None:
    """Write a single-page HTML report for a trial."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)

    title = "OrcaDolittle — trial report"
    rp = prediction.response_probs
    body = f"""
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>{html.escape(title)}</title>
<style>
:root {{ color-scheme: dark; }}
body {{ font-family: ui-serif, Georgia, serif; background:#0d1117; color:#e8e0d4;
       margin: 0; padding: 2rem; max-width: 900px; }}
h1, h2 {{ color: #c9a84c; font-weight: 500; letter-spacing: 0.02em; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ padding: 0.5rem 0.75rem; border-bottom: 1px solid #1a1714;
          text-align: left; }}
th {{ color: #c9a84c; font-weight: 500; }}
.tier {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 999px;
         background: #1a1714; color: #c9a84c; font-size: 0.85rem; }}
small {{ color: #9b9282; }}
</style></head><body>
<h1>{html.escape(title)}</h1>
<p>{html.escape(prediction.summary())}</p>

<h2>Predicted response distribution</h2>
<table>
<thead><tr><th>Response</th><th>Real stimulus</th><th>Shuffled</th><th>Scrambled</th></tr></thead>
<tbody>
{"".join(_row(k, rp.get(k, 0.0),
              prediction.counterfactual_shuffled.get(k, 0.0),
              prediction.counterfactual_scrambled.get(k, 0.0))
         for k in ("reply", "approach", "avoid", "no_response"))}
</tbody>
</table>

<h2>Falsifiability tier</h2>
<p><span class="tier">{html.escape(prediction.confidence)}</span>
&nbsp;&nbsp;<small>counterfactual Δ = {prediction.counterfactual_delta:+.3f}</small></p>

<h2>Metadata</h2>
<pre>{html.escape(repr(prediction.metadata))}</pre>

<hr style="border-color:#1a1714"/>
<p><small>Generated by <code>orcadolittle.utils.viz</code></small></p>
</body></html>
"""
    out.write_text(body, encoding="utf-8")


def _row(label: str, real: float, shuffled: float, scrambled: float) -> str:
    return (
        f"<tr><td>{html.escape(label)}</td>"
        f"<td>{real:.2f}</td><td>{shuffled:.2f}</td><td>{scrambled:.2f}</td></tr>"
    )


def encode_audio_b64(path: str | Path) -> str:
    """Return a data-URI base64 encoding of an audio file."""
    data = Path(path).read_bytes()
    return "data:audio/wav;base64," + base64.b64encode(data).decode("ascii")
